services:
  - name: authentification-model-backend
    type: web
    buildCommand: npm run build
    startCommand: npm run start
    env:
      - key: NODE_ENV
        value: production
    routes:
      - path: /api/*
        destination: authentification-model-backend
